### ISSUE TITLE
Checking typing.List attribute that doesn't exist in Python 3.7

### ISSUE THREAD

**Issue by nitzspiz** [omersaraf/IOCynergy#1]
Starting with Python 3.7 typing classes, e.g List, don't have __name__ attribute anymore.
It has changed to _name without backwards compatibility.

Cynergy however check this attribute in container.py on line 102.
![cynergy-bug](https://user-images.githubusercontent.com/45848203/64591820-56c70100-d3b3-11e9-8f22-820420655099.PNG)

Let's track the corresponding issue in typing: https://github.com/python/typing/issues/676

**Comment by omersaraf** [comment]
Thanks for letting me know!

Currently, Cynergy does not support Python3.7, only until Python 3.6. 
I'll add it to the project goals and update the code in the near future.

Stay tuned!

**Comment by omersaraf** [comment]
I added a fix and now Cynegry should support python 3.7, please make sure it works in your projects as expected :)
